# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 07:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('currency', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('highest_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('lowest_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('closing_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('adjusted_closing_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('volume', models.IntegerField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='market_data.Security')),
            ],
        ),
    ]
