# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 17:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('currency', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['symbol'],
                'verbose_name_plural': 'securities',
            },
        ),
        migrations.CreateModel(
            name='SecurityDailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('highest_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('lowest_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('closing_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('adjusted_closing_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('volume', models.IntegerField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='market_data.Security')),
            ],
            options={
                'ordering': ['date', 'security'],
                'verbose_name_plural': 'security daily data',
            },
        ),
        migrations.CreateModel(
            name='SecurityDailyMovingAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
            options={
                'ordering': ['date', 'period'],
                'verbose_name_plural': 'security daily moving averages',
            },
        ),
        migrations.CreateModel(
            name='SecurityDailyMovingAveragePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_moving_average_periods', to='market_data.Security')),
            ],
            options={
                'ordering': ['security', 'days'],
                'verbose_name_plural': 'security daily moving average periods',
            },
        ),
        migrations.AddField(
            model_name='securitydailymovingaverage',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_moving_averages', to='market_data.SecurityDailyMovingAveragePeriod'),
        ),
        migrations.AlterUniqueTogether(
            name='securitydailymovingaverageperiod',
            unique_together=set([('security', 'days')]),
        ),
        migrations.AlterUniqueTogether(
            name='securitydailymovingaverage',
            unique_together=set([('date', 'period')]),
        ),
        migrations.AlterUniqueTogether(
            name='securitydailydata',
            unique_together=set([('security', 'date')]),
        ),
    ]
