# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_security_securitydailydata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='securitydailydata',
            unique_together=set([('security', 'date')]),
        ),
    ]
