# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_auto_20170406_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterModelOptions(
            name='securitydailydata',
            options={'ordering': ['-date', 'security']},
        ),
    ]
