# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 10:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_auto_20170406_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDailyMovingAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period', models.IntegerField()),
                ('average', models.DecimalField(decimal_places=3, max_digits=12)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_moving_average', to='market_data.Security')),
            ],
            options={
                'ordering': ['date', 'security', 'period'],
            },
        ),
        migrations.AlterModelOptions(
            name='securitydailydata',
            options={'ordering': ['date', 'security']},
        ),
        migrations.AlterUniqueTogether(
            name='securitydailymovingaverage',
            unique_together=set([('security', 'date', 'period')]),
        ),
    ]
