# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 10:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_auto_20170412_0834'),
        ('analyzers', '0002_auto_20170412_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDailyMachineLearningPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('moving_average_periods', models.ManyToManyField(blank=True, null=True, to='analyzers.SecurityDailyMovingAveragePeriod')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_machine_learning_periods', to='market_data.Security')),
            ],
            options={
                'ordering': ['security', 'days'],
                'verbose_name_plural': 'security daily machine learning periods',
            },
        ),
        migrations.CreateModel(
            name='SecurityDailyMachineLearningPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prediction', models.DecimalField(decimal_places=3, max_digits=12)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_machine_learning_predictions', to='analyzers.SecurityDailyMachineLearningPeriod')),
            ],
            options={
                'ordering': ['date', 'period'],
                'verbose_name_plural': 'security daily machine learning prediction',
            },
        ),
        migrations.AlterUniqueTogether(
            name='securitydailymachinelearningprediction',
            unique_together=set([('date', 'period')]),
        ),
        migrations.AlterUniqueTogether(
            name='securitydailymachinelearningperiod',
            unique_together=set([('security', 'days')]),
        ),
    ]
